### ISSUE TITLE
no script run_xds2aimless.sh present in code

### ISSUE THREAD

**Issue by JunAishima** [legrandp/xdsme#14]
Error when running xdsme - "sh: run_xds2aimless.sh: command not found". Looks like the script was supposed to be part of the commit cb1fdb95e84183ea09748c5937f31d3f896154e8 where the run_aimless method was introduced in pointless.py

**Comment by legrandp** [comment]
Thanks for the notification. This was effectively closed a few days after in commit https://github.com/legrandp/xdsme/commit/d3398f64c88dcce260ea15aebd91bcc1d6d6f552.
