### ISSUE TITLE
Error in XDS version BUILT=20160514

### ISSUE THREAD

**Issue by ErwinP** [legrandp/xdsme#15]
Dear,

While being on the latest version of XDS, xdsme always ends with a ValueError. The last file that has been written, is an XDS.INP.00x, with the X being a number. I had this error with xdsme-0.5.0.2 download from google code, as well as while using the master branch, pulled here from github. 

I pasted the last output of xdsme [here](https://codepaste.net/5hfrom). 

If there is any other information you'd like to get from me, don't hesitate to contact me: erwin_dot_pannecoucke_at_irc_dot_vib-ugent_dot_be

Thanks a lot in advance!
Erwin

**Comment by legrandp** [comment]
Thanks Erwin for reporting this. It was fixed with commits from 25/01/2017.
