### ISSUE TITLE
Missing dependancy gives an unclear Exception

### ISSUE THREAD

**Issue by dunatotatos** [legrandp/xdsme#22]
When xds_par is not available, xdsme raises and exception which, IMHO, lacks clarity. Here is the full output of what I see

    $ xdsme --weak --slow --brute ../2679p1_1_master.h5 
    >> Interpreting header of image:  ../2679p1_1_master.h5
    >> Image format:      hdf5dec

    Simplified XDS Processing
    /bin/sh: xds_par: command not found

          xds   version:                   
          xdsme version:            0.5.5.2

        Diffraction Setup Parameters:

      Detector distance:               342.53 mm
      X-ray wavelength:                0.9801 A
      Oscillation range:               0.1000 degree

      Beam coordinate X:               1438.6 pixel
                      Y:               1731.2 pixel
      Image range:                  [1, 3600]

      Selected resolution range:       50.00 - 3.00 A
      Number of processors available:     32

    Traceback (most recent call last):
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 1898, in <module>
        R1 = newrun.run_init()
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 914, in run_init
        self.run(rsave=True)
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 805, in run
        xdsProcess = self._creat_process(self.__execfile)
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 751, in _creat_process
        universal_newlines=True)
      File "/cbrc/software/anaconda/v5.2.0.app/lib/python2.7/subprocess.py", line 394, in __init__
        errread, errwrite)
      File "/cbrc/software/anaconda/v5.2.0.app/lib/python2.7/subprocess.py", line 1047, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or director

I just realized now that `/bin/sh: xds_par: command not found` is actually included in the output. A detailed exception like `OSError("xds_par not found")` would save a lot of debugging time ;)

**Comment by dunatotatos** [comment]
A similarly unclear message appears when xds_par is available, but not H5ToXds:

    $ xdsme --weak --slow --brute ../2679p1_1_master.h5 
    >> Interpreting header of image:  ../2679p1_1_master.h5
    >> Image format:      hdf5dec

        Simplified XDS Processing

          xds   version:  Jan 26, 2018  BUILT=20180808 
          xdsme version:            0.5.5.2

        Diffraction Setup Parameters:

      Detector distance:               342.53 mm
      X-ray wavelength:                0.9801 A
      Oscillation range:               0.1000 degree

      Beam coordinate X:               1438.6 pixel
                      Y:               1731.2 pixel
      Image range:                  [1, 3600]

      Selected resolution range:       50.00 - 3.00 A
      Number of processors available:     32

    Traceback (most recent call last):
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 1898, in <module>
        R1 = newrun.run_init()
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 915, in run_init
        res = XDSLogParser("INIT.LP", run_dir=self.run_dir, verbose=1)
      File "/cbrc/software/xdsme/v0.6.2.app/bin/noarch/xdsme", line 347, in __init__
        raise IOError, "Can't read file: %s" % full_filename
    IOError: Can't read file: xdsme_2679p1_1/INIT.LP

**Comment by legrandp** [comment]
Thanks for reporting this. This was on the TODO list. It is now fixed concerning the xds_par dependence in commit c7bca8ac4df765dbd6d4e1e47598cfc185f8d841.
For H5ToXds it is more difficult to track since it is not always necessary for hdf5 processing. Moreover,  using the neggia library is now the recommanded way to go and does not depend on H5ToXds. You can have a look [here](https://github.com/legrandp/xdsme/wiki/Eiger_Dectris_HDF5) for more details.
