### ISSUE TITLE
TypeError in XIO.py, line 970

### ISSUE THREAD

**Issue by wojdyr** [legrandp/xdsme#24]
I downloaded dataset InvbN_18715_a_TK11_7jp4 from proteindiffraction.org to check xdsme.
The error I get from running `xdsme ../data/*` is
```
>> Interpreting header of image:  ../data/awm9-4.001
>> Image format:      marccd
>> Detector type:     MarCCD 300
Traceback (most recent call last):
  File "/home/wojdyr/fresh/xdsme/bin/noarch/xdsme", line 1850, in <module>
    newPar = collect.export("xds")
  File "/home/wojdyr/fresh/xdsme/XDS/XIO/XIO.py", line 970, in export
    if spec_type in self.image.header["SerialNumber"] or \
TypeError: argument of type 'NoneType' is not iterable
```

The reason why I'm trying xdsme is to check if it writes scaled unmerged data file. Does it?
I want to [summarize here][1] how different programs and pipelines write scaled unmerged data. 

[1]: https://strucbio.biologie.uni-konstanz.de/ccp4wiki/index.php?title=Scaled_unmerged_data_files

**Comment by legrandp** [comment]
Hi Marcin,
Thanks for the notification of this problem. It was a stupid regression. I have fixed it an tested it with the dataset InvbN_18715_a_TK11_7jp4. To make it work, some options are needed:

xdsme -W ../data/awm9-4.*
xdsme --O1 -r 1.8 --brute ../data/awm9-4.*
The second run will use the post-refinement results and extend the resolution to 1.8A.

Scaled and unmerged files are produced at the end:
from XDS -> XDS_ASCII.HKL
and also exported in MTZ using aimless (from XDS_ASCII.HKL without rescaling): *_aimless.mtz
