### ISSUE TITLE
Error when anglular step between images is negative.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [legrandp/xdsme#3]
```
Bonjour Pierre
Juste pour t'informer d'un mini bogue en xdsme. Mes utilisateurs
aujourd'hui ont decide (bizarrement il faut avouer!) de collecter leurs
images de test avec osc_step = -90 degres. Dans ce cas la, le script avait
un probleme avec la gamme angulaire des images. IL marchait du nouveau
quand on a collecte avec osc_step = 90 degres.


```

Original issue reported on code.google.com by `legrand.p` on 20 Feb 2010 at 10:15

**Comment by legrandp** [comment]
It is linked to XDS. There is no way to process data with negative oscillation range in XDS:
http://xds.mpimf-heidelberg.mpg.de/html_doc/xds_parameters.html#OSCILLATION_RANGE=
 It must be a positive multiple of 0.0001.
