### ISSUE TITLE
With the newest version of XDS will not import matrix file using the -M flag

### ISSUE THREAD

**Issue by GoogleCodeExporter** [legrandp/xdsme#8]
```
Please provide any additional information below.

It seems in the newest version of XDS the XPARM.XDS format has changed when I 
try to import the file xdsme fails 

```

Original issue reported on code.google.com by `sd.wee...@gmail.com` on 5 Jul 2013 at 3:22

**Comment by legrandp** [comment]
Fixed and tested with the following commit. 
https://github.com/legrandp/xdsme/commit/d3bc45b25c11df0c5b519fef3618adc8171b6087
